version: '3.8'

services:
  # Inbound Service
  inbound-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: inbound
    container_name: callcenter-inbound
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_API_KEY: ${TWILIO_API_KEY}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      TWILIO_APP_SID: ${TWILIO_APP_SID}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      ELEVENLABS_WEBHOOK: ${ELEVENLABS_WEBHOOK}
      VOICE_ID: ${VOICE_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEBHOOK_URL: ${WEBHOOK_URL}
      MONGODB_URL: ${MONGODB_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      REDIS_URL: "redis://redis:6379"
      INSTANCE_ID: "inbound-1"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - callcenter-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Outbound Service
  outbound-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: outbound
    container_name: callcenter-outbound
    ports:
      - "8500:8500"
    env_file:
      - .env
    environment:
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_API_KEY: ${TWILIO_API_KEY}
      TWILIO_API_SECRET: ${TWILIO_API_SECRET}
      TWILIO_APP_SID: ${TWILIO_APP_SID}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      ELEVENLABS_WEBHOOK: ${ELEVENLABS_WEBHOOK}
      VOICE_ID: ${VOICE_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEBHOOK_URL: ${WEBHOOK_URL}
      MONGODB_URL: ${MONGODB_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      REDIS_URL: "redis://redis:6379"
      INSTANCE_ID: "outbound-1"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - callcenter-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: callcenter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - callcenter-network
    command: >
      redis-server
      --save 60 1000
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 8mb
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  redis_data:
    driver: local

networks:
  callcenter-network:
    driver: bridge


    